import type { PG, Tenant, Complaint } from './types';

export const tenants: Tenant[] = [
  {
    id: 't-1',
    name: 'Priya Sharma',
    pgId: 'pg-1',
    pgName: 'Sunshine Living',
    bedId: 'pg1-101-a',
    rentStatus: 'paid',
    dueDate: '2024-08-05',
    rentAmount: 8500,
    kycStatus: 'verified',
    kycDocUrl: 'https://placehold.co/400x300.png',
  },
  {
    id: 't-2',
    name: 'Rohan Verma',
    pgId: 'pg-2',
    pgName: 'Royal Comforts PG',
    bedId: 'RC-205',
    rentStatus: 'unpaid',
    dueDate: '2024-08-05',
    rentAmount: 9000,
    kycStatus: 'pending',
  },
  {
    id: 't-3',
    name: 'Anjali Mehta',
    pgId: 'pg-3',
    pgName: "Students' Nest",
    bedId: 'SN-A3',
    rentStatus: 'paid',
    dueDate: '2024-08-10',
    rentAmount: 12000,
    kycStatus: 'verified',
    kycDocUrl: 'https://placehold.co/400x300.png',
  },
   {
    id: 't-4',
    name: 'Sameer Khan',
    pgId: 'pg-2',
    pgName: 'Royal Comforts PG',
    bedId: 'RC-301',
    rentStatus: 'unpaid',
    dueDate: '2024-08-05',
    rentAmount: 9500,
    kycStatus: 'rejected',
  },
  // --- Additional tenants for Sunshine Living (pg-1) ---
  {
    id: 't-5',
    name: 'Aarav Singh',
    pgId: 'pg-1',
    pgName: 'Sunshine Living',
    bedId: 'pg1-101-b',
    rentStatus: 'unpaid',
    dueDate: '2024-08-05',
    rentAmount: 8500,
    kycStatus: 'verified',
  },
  {
    id: 't-6',
    name: 'Siya Patel',
    pgId: 'pg-1',
    pgName: 'Sunshine Living',
    bedId: 'pg1-101-c',
    rentStatus: 'paid',
    dueDate: '2024-08-05',
    rentAmount: 8500,
    kycStatus: 'verified',
  },
  {
    id: 't-7',
    name: 'Vivaan Reddy',
    pgId: 'pg-1',
    pgName: 'Sunshine Living',
    bedId: 'pg1-101-d',
    rentStatus: 'paid',
    dueDate: '2024-08-05',
    rentAmount: 8500,
    kycStatus: 'verified',
  },
  {
    id: 't-8',
    name: 'Diya Gupta',
    pgId: 'pg-1',
    pgName: 'Sunshine Living',
    bedId: 'pg1-102-a',
    rentStatus: 'paid',
    dueDate: '2024-08-05',
    rentAmount: 8500,
    kycStatus: 'verified',
  },
  {
    id: 't-9',
    name: 'Aryan Kumar',
    pgId: 'pg-1',
    pgName: 'Sunshine Living',
    bedId: 'pg1-102-b',
    rentStatus: 'paid',
    dueDate: '2024-08-05',
    rentAmount: 8500,
    kycStatus: 'verified',
  },
  {
    id: 't-10',
    name: 'Ananya Rao',
    pgId: 'pg-1',
    pgName: 'Sunshine Living',
    bedId: 'pg1-102-c',
    rentStatus: 'paid',
    dueDate: '2024-08-05',
    rentAmount: 8500,
    kycStatus: 'verified',
    hasMessage: true,
  },
  { id: 't-11', name: 'Kabir Joshi', pgId: 'pg-1', pgName: 'Sunshine Living', bedId: 'pg1-102-d', rentStatus: 'paid', dueDate: '2024-08-05', rentAmount: 8500, kycStatus: 'verified' },
  { id: 't-12', name: 'Myra Sharma', pgId: 'pg-1', pgName: 'Sunshine Living', bedId: 'pg1-103-a', rentStatus: 'paid', dueDate: '2024-08-05', rentAmount: 8500, kycStatus: 'verified' },
  { id: 't-13', name: 'Reyansh Singh', pgId: 'pg-1', pgName: 'Sunshine Living', bedId: 'pg1-103-b', rentStatus: 'paid', dueDate: '2024-08-05', rentAmount: 8500, kycStatus: 'verified' },
  { id: 't-14', name: 'Aisha Khan', pgId: 'pg-1', pgName: 'Sunshine Living', bedId: 'pg1-103-c', rentStatus: 'paid', dueDate: '2024-08-05', rentAmount: 8500, kycStatus: 'verified' },
  { id: 't-15', name: 'Advik Verma', pgId: 'pg-1', pgName: 'Sunshine Living', bedId: 'pg1-103-d', rentStatus: 'paid', dueDate: '2024-08-05', rentAmount: 8500, kycStatus: 'verified' },
  { id: 't-16', name: 'Kiara Reddy', pgId: 'pg-1', pgName: 'Sunshine Living', bedId: 'pg1-104-a', rentStatus: 'paid', dueDate: '2024-08-05', rentAmount: 8500, kycStatus: 'verified' },
  { id: 't-17', name: 'Ishaan Patel', pgId: 'pg-1', pgName: 'Sunshine Living', bedId: 'pg1-104-b', rentStatus: 'paid', dueDate: '2024-08-05', rentAmount: 8500, kycStatus: 'verified' },
  { id: 't-18', name: 'Zara Mehta', pgId: 'pg-1', pgName: 'Sunshine Living', bedId: 'pg1-104-c', rentStatus: 'unpaid', dueDate: '2024-08-05', rentAmount: 8500, kycStatus: 'verified' },
  { id: 't-19', name: 'Arjun Gupta', pgId: 'pg-1', pgName: 'Sunshine Living', bedId: 'pg1-104-d', rentStatus: 'paid', dueDate: '2024-08-05', rentAmount: 8500, kycStatus: 'verified' },
];


export const pgs: PG[] = [
  {
    id: 'pg-1',
    name: 'Sunshine Living',
    location: 'Koramangala, Bangalore',
    city: 'Bangalore',
    gender: 'female',
    priceRange: { min: 8000, max: 15000 },
    amenities: ['wifi', 'ac', 'food', 'laundry'],
    images: [
      'https://placehold.co/600x400.png',
      'https://placehold.co/600x400.png',
      'https://placehold.co/600x400.png',
    ],
    rating: 4.5,
    occupancy: 18,
    totalBeds: 20,
    rules: ['No smoking', 'No pets', 'Visitors allowed until 10 PM'],
    contact: '+911234567890',
    rooms: [
      { id: 'room-101', name: 'Room 101', beds: [
        { id: 'pg1-101-a', name: 'A', tenantId: 't-1' },
        { id: 'pg1-101-b', name: 'B', tenantId: 't-5' },
        { id: 'pg1-101-c', name: 'C', tenantId: 't-6' },
        { id: 'pg1-101-d', name: 'D', tenantId: 't-7' },
      ]},
      { id: 'room-102', name: 'Room 102', beds: [
        { id: 'pg1-102-a', name: 'A', tenantId: 't-8' },
        { id: 'pg1-102-b', name: 'B', tenantId: 't-9' },
        { id: 'pg1-102-c', name: 'C', tenantId: 't-10' },
        { id: 'pg1-102-d', name: 'D', tenantId: 't-11' },
      ]},
      { id: 'room-103', name: 'Room 103', beds: [
        { id: 'pg1-103-a', name: 'A', tenantId: 't-12' },
        { id: 'pg1-103-b', name: 'B', tenantId: 't-13' },
        { id: 'pg1-103-c', name: 'C', tenantId: 't-14' },
        { id: 'pg1-103-d', name: 'D', tenantId: 't-15' },
      ]},
      { id: 'room-104', name: 'Room 104', beds: [
        { id: 'pg1-104-a', name: 'A', tenantId: 't-16' },
        { id: 'pg1-104-b', name: 'B', tenantId: 't-17' },
        { id: 'pg1-104-c', name: 'C', tenantId: 't-18' },
        { id: 'pg1-104-d', name: 'D', tenantId: 't-19' },
      ]},
      { id: 'room-105', name: 'Room 105', beds: [
        { id: 'pg1-105-a', name: 'A', tenantId: null },
        { id: 'pg1-105-b', name: 'B', tenantId: null },
        { id: 'pg1-105-c', name: 'C', tenantId: null },
        { id: 'pg1-105-d', name: 'D', tenantId: null },
      ]},
    ],
  },
  {
    id: 'pg-2',
    name: 'Royal Comforts PG',
    location: 'HSR Layout, Bangalore',
    city: 'Bangalore',
    gender: 'male',
    priceRange: { min: 9000, max: 18000 },
    amenities: ['wifi', 'ac', 'power-backup', 'tv', 'parking'],
    images: ['https://placehold.co/600x400.png'],
    rating: 4.8,
    occupancy: 25,
    totalBeds: 25,
    rules: ['No loud music after 11 PM'],
    contact: '+911234567890',
  },
  {
    id: 'pg-3',
    name: "Students' Nest",
    location: 'Andheri West, Mumbai',
    city: 'Mumbai',
    gender: 'co-ed',
    priceRange: { min: 10000, max: 20000 },
    amenities: ['wifi', 'food', 'laundry'],
    images: ['https://placehold.co/600x400.png'],
    rating: 4.2,
    occupancy: 35,
    totalBeds: 40,
    rules: ['Respect quiet hours'],
    contact: '+911234567890',
  },
  {
    id: 'pg-4',
    name: 'Home Haven PG',
    location: 'Gachibowli, Hyderabad',
    city: 'Hyderabad',
    gender: 'female',
    priceRange: { min: 7500, max: 14000 },
    amenities: ['wifi', 'ac', 'food', 'power-backup', 'tv'],
    images: ['https://placehold.co/600x400.png'],
    rating: 4.6,
    occupancy: 28,
    totalBeds: 30,
    rules: [],
    contact: '+911234567890',
  },
];

export const complaints: Complaint[] = [
  {
    id: 'c-1',
    tenantId: 't-2',
    tenantName: 'Rohan Verma',
    pgId: 'pg-2',
    category: 'wifi',
    description: 'The WiFi speed is very slow in my room (RC-205).',
    status: 'open',
    date: '2024-07-28',
  },
  {
    id: 'c-2',
    tenantId: 't-1',
    tenantName: 'Priya Sharma',
    pgId: 'pg-1',
    category: 'cleanliness',
    description: 'The common bathroom on the 1st floor has not been cleaned today.',
    status: 'in-progress',
    date: '2024-07-29',
  },
  {
    id: 'c-3',
    tenantId: 't-7',
    tenantName: 'Vivaan Reddy',
    pgId: 'pg-1',
    category: 'maintenance',
    description: 'My room lights are flickering.',
    status: 'open',
    date: '2024-07-30',
  },
];
