
import type { PG, Guest, Complaint, Expense, Menu, Staff, User, Plan, PlanName } from './types';

export const defaultMenu: Menu = {
  monday: { breakfast: 'Poha, Tea', lunch: 'Roti, Mixed Veg, Dal Tadka, Rice', dinner: 'Paneer Butter Masala, Roti, Salad' },
  tuesday: { breakfast: 'Upma, Coffee', lunch: 'Roti, Aloo Gobi, Dal Fry, Rice', dinner: 'Chole, Bhature, Onion Salad' },
  wednesday: { breakfast: 'Idli Sambar', lunch: 'Roti, Rajma, Jeera Rice', dinner: 'Veg Pulao, Raita, Papad' },
  thursday: { breakfast: 'Aloo Paratha, Curd', lunch: 'Roti, Bhindi Masala, Dal Makhani, Rice', dinner: 'Kadhi Pakoda, Rice, Roti' },
  friday: { breakfast: 'Masala Dosa', lunch: 'Roti, Lauki Sabzi, Chana Dal, Rice', dinner: 'Veg Biryani, Raita' },
  saturday: { breakfast: 'Bread Omelette', lunch: 'Roti, Baingan Bharta, Arhar Dal, Rice', dinner: 'Pav Bhaji' },
  sunday: { breakfast: 'Puri Sabji', lunch: 'Special Thali (Chef\'s choice)', dinner: 'Noodles, Manchurian' },
}

export const plans: Record<PlanName, Plan> = {
  free: {
    id: 'free',
    name: 'Free',
    price: 0,
    pricePeriod: 'Forever',
    description: "For single PG owners using local storage. No cloud backup.",
    pgLimit: 1,
    hasComplaints: true,
    hasStaffManagement: false,
    hasAiRentReminders: false,
    hasSeoGenerator: false,
    hasAutomatedWhatsapp: false,
    hasMarketplace: false,
    hasCloudSync: false,
  },
  starter: {
    id: 'starter',
    name: 'Starter',
    price: 99,
    pricePeriod: '/pg/month',
    description: "For growing businesses managing up to 5 properties.",
    pgLimit: 5,
    hasComplaints: true,
    hasStaffManagement: true,
    hasAiRentReminders: true,
    hasSeoGenerator: true,
    hasAutomatedWhatsapp: false,
    hasMarketplace: false,
    hasCloudSync: true,
  },
  pro: {
    id: 'pro',
    name: 'Pro',
    price: 199,
    pricePeriod: '/pg/month',
    description: "Unlock powerful automation and analytics for unlimited PGs.",
    pgLimit: 'unlimited',
    hasComplaints: true,
    hasStaffManagement: true,
    hasAiRentReminders: true,
    hasSeoGenerator: true,
    hasAutomatedWhatsapp: true,
    hasMarketplace: false,
    hasCloudSync: true,
  },
  business: {
      id: 'business',
      name: 'Business',
      price: 399,
      pricePeriod: '/pg/month',
      description: "Advanced tools for scaling operators.",
      pgLimit: 10,
      hasComplaints: true,
      hasStaffManagement: true,
      hasAiRentReminders: true,
      hasSeoGenerator: true,
      hasAutomatedWhatsapp: true,
      hasMarketplace: false,
      hasCloudSync: true,
  },
  enterprise: {
    id: 'enterprise',
    name: 'Enterprise',
    price: 'Custom',
    pricePeriod: "",
    description: "List your PG on our marketplace for maximum visibility.",
    pgLimit: 'unlimited',
    hasComplaints: true,
    hasStaffManagement: true,
    hasAiRentReminders: true,
    hasSeoGenerator: true,
    hasAutomatedWhatsapp: true,
    hasMarketplace: true,
    hasCloudSync: true,
  }
};


export const users: User[] = [
  {
    id: 'user-1',
    name: 'P. G. Owner',
    email: 'owner@pgoasis.com',
    phone: '+919999999999',
    role: 'owner',
    avatarUrl: 'https://placehold.co/40x40.png?text=PO',
    subscription: { planId: 'pro', status: 'active' },
  },
  {
    id: 'user-2',
    name: 'Manoj Sharma',
    email: 'manager@pgoasis.com',
    phone: '+918888888888',
    role: 'manager',
    pgIds: ['pg-1'],
    avatarUrl: 'https://placehold.co/40x40.png?text=MS',
    subscription: { planId: 'pro', status: 'active' }, 
  },
  {
    id: 'user-3',
    name: 'Sita Devi',
    email: 'cook@pgoasis.com',
    phone: '+917777777777',
    role: 'cook',
    pgIds: ['pg-1'],
    avatarUrl: 'https://placehold.co/40x40.png?text=SD',
    subscription: { planId: 'pro', status: 'active' },
  },
  {
    id: 'user-4',
    name: 'Priya Sharma',
    email: 'guest@pgoasis.com',
    phone: '+919876543210',
    role: 'tenant',
    guestId: 't-1',
    avatarUrl: 'https://placehold.co/40x40.png?text=PS',
  },
];


export const guests: Guest[] = [
  {
    id: 't-1',
    name: 'Priya Sharma',
    phone: '+919876543210',
    email: 'guest@pgoasis.com',
    pgId: 'pg-1',
    pgName: 'Sunshine Living',
    bedId: 'pg1-101-a',
    rentStatus: 'paid',
    rentPaidAmount: 8500,
    dueDate: '2024-08-05',
    rentAmount: 8500,
    depositAmount: 17000,
    kycStatus: 'verified',
    kycDocUrl: 'https://placehold.co/400x300.png',
    moveInDate: '2024-03-01',
    noticePeriodDays: 30,
  },
  {
    id: 't-2',
    name: 'Rohan Verma',
    phone: '+919876543211',
    email: 'rohan.verma@example.com',
    pgId: 'pg-2',
    pgName: 'Royal Comforts PG',
    bedId: 'RC-205',
    rentStatus: 'unpaid',
    rentPaidAmount: 0,
    dueDate: '2024-08-05',
    rentAmount: 9000,
    depositAmount: 18000,
    kycStatus: 'pending',
    moveInDate: '2024-05-15',
    noticePeriodDays: 30,
  },
  {
    id: 't-3',
    name: 'Anjali Mehta',
    phone: '+919876543212',
    email: 'anjali.mehta@example.com',
    pgId: 'pg-3',
    pgName: "Students' Nest",
    bedId: 'SN-A3',
    rentStatus: 'paid',
    rentPaidAmount: 12000,
    dueDate: '2024-08-10',
    rentAmount: 12000,
    depositAmount: 24000,
    kycStatus: 'verified',
    kycDocUrl: 'https://placehold.co/400x300.png',
    moveInDate: '2023-11-20',
    noticePeriodDays: 60,
  },
   {
    id: 't-4',
    name: 'Sameer Khan',
    phone: '+919876543213',
    email: 'sameer.khan@example.com',
    pgId: 'pg-2',
    pgName: 'Royal Comforts PG',
    bedId: 'RC-301',
    rentStatus: 'unpaid',
    rentPaidAmount: 0,
    dueDate: '2024-08-05',
    rentAmount: 9500,
    depositAmount: 19000,
    kycStatus: 'rejected',
    moveInDate: '2024-07-01',
    noticePeriodDays: 30,
  },
  // --- Additional guests for Sunshine Living (pg-1) ---
  {
    id: 't-5',
    name: 'Aarav Singh',
    pgId: 'pg-1',
    pgName: 'Sunshine Living',
    bedId: 'pg1-101-b',
    rentStatus: 'paid',
    rentPaidAmount: 8500,
    dueDate: '2024-08-05',
    rentAmount: 8500,
    depositAmount: 17000,
    kycStatus: 'verified',
    moveInDate: '2024-02-10',
    noticePeriodDays: 30,
  },
  {
    id: 't-6',
    name: 'Siya Patel',
    pgId: 'pg-1',
    pgName: 'Sunshine Living',
    bedId: 'pg1-101-c',
    rentStatus: 'paid',
    rentPaidAmount: 8500,
    dueDate: '2024-08-05',
    rentAmount: 8500,
    depositAmount: 17000,
    kycStatus: 'verified',
    moveInDate: '2024-04-12',
    noticePeriodDays: 30,
  },
  {
    id: 't-7',
    name: 'Vivaan Reddy',
    pgId: 'pg-1',
    pgName: 'Sunshine Living',
    bedId: 'pg1-101-d',
    rentStatus: 'paid',
    rentPaidAmount: 8500,
    dueDate: '2024-08-05',
    rentAmount: 8500,
    depositAmount: 17000,
    kycStatus: 'verified',
    moveInDate: '2024-01-05',
    noticePeriodDays: 30,
  },
  {
    id: 't-8',
    name: 'Diya Gupta',
    pgId: 'pg-1',
    pgName: 'Sunshine Living',
    bedId: 'pg1-102-a',
    rentStatus: 'paid',
    rentPaidAmount: 8500,
    dueDate: '2024-08-05',
    rentAmount: 8500,
    depositAmount: 17000,
    kycStatus: 'verified',
    moveInDate: '2023-12-01',
    noticePeriodDays: 30,
  },
  {
    id: 't-9',
    name: 'Aryan Kumar',
    pgId: 'pg-1',
    pgName: 'Sunshine Living',
    bedId: 'pg1-102-b',
    rentStatus: 'paid',
    rentPaidAmount: 8500,
    dueDate: '2024-08-05',
    rentAmount: 8500,
    depositAmount: 17000,
    kycStatus: 'verified',
    moveInDate: '2024-06-20',
    noticePeriodDays: 30,
  },
  {
    id: 't-10',
    name: 'Ananya Rao',
    pgId: 'pg-1',
    pgName: 'Sunshine Living',
    bedId: 'pg1-102-c',
    rentStatus: 'paid',
    rentPaidAmount: 8500,
    dueDate: '2024-08-05',
    rentAmount: 8500,
    depositAmount: 17000,
    kycStatus: 'verified',
    hasMessage: true,
    moveInDate: '2024-03-18',
    noticePeriodDays: 30,
  },
  { id: 't-11', name: 'Kabir Joshi', pgId: 'pg-1', pgName: 'Sunshine Living', bedId: 'pg1-102-d', rentStatus: 'paid', rentPaidAmount: 8500, dueDate: '2024-08-05', rentAmount: 8500, depositAmount: 17000, kycStatus: 'verified', moveInDate: '2024-07-07', noticePeriodDays: 30, },
  { id: 't-12', name: 'Myra Sharma', pgId: 'pg-1', pgName: 'Sunshine Living', bedId: 'pg1-201-a', rentStatus: 'paid', rentPaidAmount: 8000, dueDate: '2024-08-05', rentAmount: 8000, depositAmount: 16000, kycStatus: 'verified', moveInDate: '2024-02-22', noticePeriodDays: 30, },
  { id: 't-13', name: 'Reyansh Singh', pgId: 'pg-1', pgName: 'Sunshine Living', bedId: 'pg1-201-b', rentStatus: 'paid', rentPaidAmount: 8000, dueDate: '2024-08-05', rentAmount: 8000, depositAmount: 16000, kycStatus: 'verified', moveInDate: '2024-01-30', noticePeriodDays: 30, },
  { id: 't-14', name: 'Aisha Khan', pgId: 'pg-1', pgName: 'Sunshine Living', bedId: 'pg1-201-c', rentStatus: 'paid', rentPaidAmount: 8000, dueDate: '2024-08-05', rentAmount: 8000, depositAmount: 16000, kycStatus: 'verified', moveInDate: '2024-05-01', noticePeriodDays: 30, },
  { id: 't-15', name: 'Advik Verma', pgId: 'pg-1', pgName: 'Sunshine Living', bedId: 'pg1-201-d', rentStatus: 'paid', rentPaidAmount: 8000, dueDate: '2024-08-05', rentAmount: 8000, depositAmount: 16000, kycStatus: 'verified', moveInDate: '2024-03-03', noticePeriodDays: 30, },
  { id: 't-16', name: 'Kiara Reddy', pgId: 'pg-1', pgName: 'Sunshine Living', bedId: 'pg1-201-e', rentStatus: 'paid', rentPaidAmount: 8000, dueDate: '2024-08-05', rentAmount: 8000, depositAmount: 16000, kycStatus: 'verified', moveInDate: '2024-04-09', noticePeriodDays: 30, },
  { id: 't-18', name: 'Zara Mehta', pgId: 'pg-1', pgName: 'Sunshine Living', bedId: 'pg1-202-a', rentStatus: 'unpaid', rentPaidAmount: 0, dueDate: '2024-08-05', rentAmount: 9000, depositAmount: 18000, kycStatus: 'verified', moveInDate: '2024-01-15', noticePeriodDays: 30, },
  { id: 't-19', name: 'Arjun Gupta', pgId: 'pg-1', pgName: 'Sunshine Living', bedId: 'pg1-202-b', rentStatus: 'paid', rentPaidAmount: 9000, dueDate: '2024-08-05', rentAmount: 9000, depositAmount: 18000, kycStatus: 'verified', moveInDate: '2024-02-01', noticePeriodDays: 30, },
  { id: 't-20', name: 'Isha Desai', pgId: 'pg-1', pgName: 'Sunshine Living', bedId: 'pg1-202-c', rentStatus: 'partial', rentPaidAmount: 4000, dueDate: '2024-08-05', rentAmount: 9000, depositAmount: 18000, kycStatus: 'verified', moveInDate: '2024-07-05', noticePeriodDays: 30, },
];


export const pgs: PG[] = [
  {
    id: 'pg-1',
    name: 'Sunshine Living',
    location: 'Koramangala, Bangalore',
    city: 'Bangalore',
    gender: 'female',
    priceRange: { min: 8000, max: 15000 },
    amenities: ['wifi', 'ac', 'food', 'laundry'],
    images: [
      'https://placehold.co/600x400.png',
      'https://placehold.co/600x400.png',
      'https://placehold.co/600x400.png',
    ],
    rating: 4.5,
    occupancy: 17,
    totalBeds: 20,
    rules: ['No smoking in rooms', 'No pets allowed', 'Visitors allowed in common areas until 10 PM', 'Quiet hours are from 11 PM to 7 AM'],
    contact: '+911234567890',
    ownerId: 'user-1',
    floors: [
      { id: 'floor-1', name: 'First Floor', rooms: [
        { id: 'room-101', name: 'Room 101', rent: 8500, deposit: 17000, beds: [
          { id: 'pg1-101-a', name: 'A', guestId: 't-1' },
          { id: 'pg1-101-b', name: 'B', guestId: 't-5' },
          { id: 'pg1-101-c', name: 'C', guestId: 't-6' },
          { id: 'pg1-101-d', name: 'D', guestId: 't-7' },
        ]},
        { id: 'room-102', name: 'Room 102', rent: 8500, deposit: 17000, beds: [
          { id: 'pg1-102-a', name: 'A', guestId: 't-8' },
          { id: 'pg1-102-b', name: 'B', guestId: 't-9' },
          { id: 'pg1-102-c', name: 'C', guestId: 't-10' },
          { id: 'pg1-102-d', name: 'D', guestId: 't-11' },
        ]},
      ]},
      { id: 'floor-2', name: 'Second Floor', rooms: [
        { id: 'room-201', name: 'Room 201', rent: 8000, deposit: 16000, beds: [
          { id: 'pg1-201-a', name: 'A', guestId: 't-12' },
          { id: 'pg1-201-b', name: 'B', guestId: 't-13' },
          { id: 'pg1-201-c', name: 'C', guestId: 't-14' },
          { id: 'pg1-201-d', name: 'D', guestId: 't-15' },
          { id: 'pg1-201-e', name: 'E', guestId: 't-16' },
          { id: 'pg1-201-f', name: 'F', guestId: null },
        ]},
        { id: 'room-202', name: 'Room 202', rent: 9000, deposit: 18000, beds: [
          { id: 'pg1-202-a', name: 'A', guestId: 't-18' },
          { id: 'pg1-202-b', name: 'B', guestId: 't-19' },
          { id: 'pg1-202-c', name: 'C', guestId: 't-20' },
          { id: 'pg1-202-d', name: 'D', guestId: null },
        ]},
      ]},
    ],
    menu: defaultMenu,
  },
  {
    id: 'pg-2',
    name: 'Royal Comforts PG',
    location: 'HSR Layout, Bangalore',
    city: 'Bangalore',
    gender: 'male',
    priceRange: { min: 9000, max: 18000 },
    amenities: ['wifi', 'ac', 'power-backup', 'tv', 'parking'],
    images: ['https://placehold.co/600x400.png'],
    rating: 4.8,
    occupancy: 2,
    totalBeds: 25,
    rules: ['No loud music after 11 PM'],
    contact: '+911234567890',
    ownerId: 'user-1',
    floors: [],
    menu: defaultMenu,
  },
  {
    id: 'pg-3',
    name: "Students' Nest",
    location: 'Andheri West, Mumbai',
    city: 'Mumbai',
    gender: 'co-ed',
    priceRange: { min: 10000, max: 20000 },
    amenities: ['wifi', 'food', 'laundry'],
    images: ['https://placehold.co/600x400.png'],
    rating: 4.2,
    occupancy: 1,
    totalBeds: 40,
    rules: ['Respect quiet hours'],
    contact: '+911234567890',
    ownerId: 'user-1',
    floors: [],
    menu: defaultMenu,
  },
  {
    id: 'pg-4',
    name: 'Home Haven PG',
    location: 'Gachibowli, Hyderabad',
    city: 'Hyderabad',
    gender: 'female',
    priceRange: { min: 7500, max: 14000 },
    amenities: ['wifi', 'ac', 'food', 'power-backup', 'tv'],
    images: ['https://placehold.co/600x400.png'],
    rating: 4.6,
    occupancy: 0,
    totalBeds: 30,
    rules: [],
    contact: '+911234567890',
    ownerId: 'user-1',
    floors: [],
    menu: defaultMenu,
  },
];

export const complaints: Complaint[] = [
  {
    id: 'c-1',
    guestId: 't-2',
    guestName: 'Rohan Verma',
    pgId: 'pg-2',
    pgName: 'Royal Comforts PG',
    category: 'wifi',
    description: 'The WiFi speed is very slow in my room (RC-205).',
    status: 'open',
    date: '2024-07-28',
    upvotes: 1,
  },
  {
    id: 'c-2',
    guestId: 't-1',
    guestName: 'Priya Sharma',
    pgId: 'pg-1',
    pgName: 'Sunshine Living',
    category: 'cleanliness',
    description: 'The common bathroom on the 1st floor has not been cleaned today.',
    status: 'in-progress',
    date: '2024-07-29',
    upvotes: 3,
  },
  {
    id: 'c-3',
    guestId: 't-7',
    guestName: 'Vivaan Reddy',
    pgId: 'pg-1',
    pgName: 'Sunshine Living',
    category: 'maintenance',
    description: 'My room lights are flickering.',
    status: 'open',
    date: '2024-07-30',
    upvotes: 0,
  },
];

export const expenses: Expense[] = [
  {
    id: 'exp-1',
    pgId: 'pg-1',
    pgName: 'Sunshine Living',
    category: 'food',
    description: 'Weekly vegetable purchase',
    amount: 7500,
    date: '2024-07-28',
  },
  {
    id: 'exp-2',
    pgId: 'pg-1',
    pgName: 'Sunshine Living',
    category: 'maintenance',
    description: 'Plumbing repair in Room 201',
    amount: 1200,
    date: '2024-07-27',
  },
  {
    id: 'exp-3',
    pgId: 'pg-2',
    pgName: 'Royal Comforts PG',
    category: 'utilities',
    description: 'Electricity Bill - July',
    amount: 15000,
    date: '2024-07-25',
  },
  {
    id: 'exp-4',
    pgId: 'pg-1',
    pgName: 'Sunshine Living',
    category: 'food',
    description: 'Groceries and staples',
    amount: 12000,
    date: '2024-07-22',
  },
   {
    id: 'exp-5',
    pgId: 'pg-1',
    pgName: 'Sunshine Living',
    category: 'salary',
    description: 'Salary for cleaning staff',
    amount: 8000,
    date: '2024-07-31',
  },
];

export const staff: Staff[] = [
  {
    id: 'staff-1',
    name: 'Rajesh Kumar',
    role: 'manager',
    phone: '+919988776655',
    salary: 25000,
    pgId: 'pg-1',
    pgName: 'Sunshine Living',
  },
  {
    id: 'staff-2',
    name: 'Sita Devi',
    role: 'cook',
    phone: '+919988776654',
    salary: 15000,
    pgId: 'pg-1',
    pgName: 'Sunshine Living',
  },
  {
    id: 'staff-3',
    name: 'Ramu Kaka',
    role: 'cleaner',
    phone: '+919988776653',
    salary: 12000,
    pgId: 'pg-1',
    pgName: 'Sunshine Living',
  },
   {
    id: 'staff-4',
    name: 'Vijay Singh',
    role: 'security',
    phone: '+919988776652',
    salary: 18000,
    pgId: 'pg-2',
    pgName: 'Royal Comforts PG',
  },
];
