import { z } from 'zod';
import { CURRENT_SCHEMA_VERSION } from './types';

export const PGSchema = z.object({
    id: z.string(),
    name: z.string(),
    location: z.string(),
    city: z.string().optional(),
    gender: z.enum(['male', 'female', 'co-ed']).optional(),
    priceRange: z.object({
        min: z.number(),
        max: z.number(),
    }).optional(),
    rating: z.number().optional(),
    occupancy: z.number().optional(),
    totalBeds: z.number().optional(),
    totalRooms: z.number().optional(),
    contact: z.string().optional(),
    ownerId: z.string(),
    status: z.enum(['active', 'pending_approval', 'rejected', 'suspended']).default('active'),
    paymentMode: z.enum(['DIRECT_UPI', 'GATEWAY', 'CASH_ONLY']).optional(),
    upiId: z.string().optional(),
    payeeName: z.string().optional(),
    qrCodeImage: z.string().optional(),
    online_payment_enabled: z.boolean().default(true),
    direct_upi_enabled: z.boolean().default(true),
    schemaVersion: z.number().default(CURRENT_SCHEMA_VERSION),
}).passthrough(); // allows other fields to pass through without being stripped

export const GuestSchema = z.object({
    id: z.string(),
    shortId: z.string().optional(),
    name: z.string(),
    phone: z.string().optional(),
    email: z.string().optional(),
    pgId: z.string(),
    pgName: z.string().optional(),
    bedId: z.string(),
    roomId: z.string().optional(),
    rentStatus: z.enum(['paid', 'unpaid', 'partial']).default('unpaid'),
    dueDate: z.string().optional(),
    rentAmount: z.number().default(0),
    depositAmount: z.number().default(0),
    amountType: z.enum(['numeric', 'symbolic']).default('numeric'),
    symbolicRentValue: z.string().optional(),
    symbolicDepositValue: z.string().optional(),
    symbolicBalance: z.string().optional(),
    kycStatus: z.enum(['not-started', 'pending', 'verified', 'rejected']).default('not-started'),
    moveInDate: z.string().optional(),
    noticePeriodDays: z.number().default(30),
    rentCycleUnit: z.enum(['minutes', 'hours', 'days', 'weeks', 'months']).default('months'),
    rentCycleValue: z.number().default(1),
    billingAnchorDay: z.number().default(1),
    isVacated: z.boolean().default(false),
    schemaVersion: z.number().default(CURRENT_SCHEMA_VERSION),
}).passthrough();

export const PaymentSchema = z.object({
    id: z.string(),
    date: z.string(),
    amount: z.number(),
    amountType: z.enum(['numeric', 'symbolic']).default('numeric'),
    symbolicValue: z.string().optional(),
    method: z.enum(['cash', 'upi', 'in-app', 'direct_upi', 'gateway', 'DIRECT_UPI']),
    forMonth: z.string(),
    notes: z.string().optional(),
    status: z.enum(['INITIATED', 'CLAIMED_PAID', 'VERIFIED', 'REJECTED', 'pending']).optional(),
    verificationStatus: z.enum(['PENDING', 'VERIFIED', 'REJECTED']).optional(),
    utr: z.string().optional(),
    screenshotUrl: z.string().optional(),
    verifiedBy: z.string().optional(),
    verifiedAt: z.string().optional(),
    claimedAt: z.string().optional(),
    createdAt: z.string().optional(),
    schemaVersion: z.number().default(CURRENT_SCHEMA_VERSION),
}).passthrough();

export const ComplaintSchema = z.object({
    id: z.string(),
    guestId: z.string().nullable(),
    guestName: z.string(),
    pgId: z.string(),
    category: z.enum(['maintenance', 'cleanliness', 'wifi', 'food', 'other']),
    description: z.string(),
    status: z.enum(['open', 'in-progress', 'resolved']).default('open'),
    date: z.string(),
    isPublic: z.boolean().default(false),
    schemaVersion: z.number().default(CURRENT_SCHEMA_VERSION),
}).passthrough();

export const RoomSchema = z.object({
    id: z.string(),
    name: z.string(),
    rent: z.number().default(0),
    deposit: z.number().default(0),
    amountType: z.enum(['numeric', 'symbolic']).default('numeric'),
    symbolicRentValue: z.string().optional(),
    symbolicDepositValue: z.string().optional(),
    amenities: z.array(z.string()).optional(),
    floorId: z.string(),
    pgId: z.string(),
}).passthrough();
