
import type { Metadata, Viewport } from 'next';
import './globals.css';
import { Toaster } from "@/components/ui/toaster"
import Header from '@/components/header';
import StoreProvider from '@/components/StoreProvider';

const APP_NAME = "RoomBox";
const APP_DESCRIPTION = "Simplify your rental property management with RoomBox. The modern OS for co-living, PGs, and hostels. Automate rent collection, track expenses, and manage tenants with ease. Get started for free.";

export const metadata: Metadata = {
  applicationName: APP_NAME,
  title: {
    default: "RoomBox | All-in-One Rental Management Software",
    template: `%s - ${APP_NAME}`,
  },
  description: APP_DESCRIPTION,
  manifest: '/manifest.json',
  keywords: [
      "rental management software",
      "property management",
      "co-living software",
      "pg management app",
      "hostel management",
      "tenant management",
      "rent collection",
      "expense tracking",
      "occupancy management",
      "RoomBox"
  ],
  authors: [{ name: "RoomBox Team" }],
  creator: "RoomBox",
};

export const viewport: Viewport = {
  themeColor: "#E2F3FD",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="!scroll-smooth">
      <head>
        {/* The <meta name="theme-color" ... /> is generated by the viewport export */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet" />
      </head>
      <body className="font-body antialiased">
        <StoreProvider>
          <div className="flex min-h-screen flex-col">
            <Header />
            <main className="flex-1">{children}</main>
          </div>
          <Toaster />
        </StoreProvider>
      </body>
    </html>
  );
}
